# Generated by Django 4.2.2 on 2023-06-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=2, upload_to='gallary'),
            preserve_default=False,
        ),
    ]
